# Generated by Django 4.1.5 on 2023-04-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_complaints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cnn_models",
            name="eye_model",
            field=models.FileField(upload_to="models/"),
        ),
        migrations.AlterField(
            model_name="cnn_models",
            name="mouth_model",
            field=models.FileField(upload_to="models/"),
        ),
        migrations.AlterField(
            model_name="complaints",
            name="footage",
            field=models.FileField(upload_to="footages/"),
        ),
    ]
