# Generated by Django 5.1 on 2024-08-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CNN_Models',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('eye_model', models.FileField(upload_to='models/')),
                ('mouth_model', models.FileField(upload_to='models/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('complaintID', models.AutoField(primary_key=True, serialize=False)),
                ('footage', models.FileField(upload_to='footages/')),
                ('comments', models.TextField(max_length=500)),
                ('username', models.TextField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
