# Generated by Django 5.1 on 2024-08-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trained_Models',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('blink_model', models.FileField(upload_to='models/')),
                ('yawning_model', models.FileField(upload_to='models/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CNN_Models',
        ),
    ]
