# Generated by Django 5.1 on 2024-08-30 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_trained_models_delete_cnn_models'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Complaints',
            new_name='Complaint',
        ),
        migrations.RenameModel(
            old_name='Trained_Models',
            new_name='Trained_Model',
        ),
    ]
