# Generated by Django 4.1.5 on 2023-04-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CNN_Models",
            fields=[
                ("sno", models.AutoField(primary_key=True, serialize=False)),
                ("eye_model", models.FilePathField()),
                ("mouth_model", models.FilePathField()),
            ],
        ),
    ]
